# Generated by Django 5.0.6 on 2024-06-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Index'},
        ),
    ]
